#server.port=8521

#spring.application.name=demo-feign

#eureka.client.service-url.defaultZone=http://localhost:8500/eureka/

server:
  port: 8521
spring:
  application:
    name: demo-feign
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka/